#' US States bordering an ocean
#'
#' For the 50 states, whether or not the state borders an ocean.
#' Note that Washington, D.C. is not included
#'
#' \itemize{
#'   \item state. Name of the state
#'   \item ocean. "yes" or "no".
#' }
#'
#' @format A data frame with 50 rows and 2 variables
#' @source Generated by hand by DTK on 2016-01-10
"Ocean_states"